local Library = {main_color = Color3.fromRGB(41,74,122), min_size = Vector2.new(400,300), toggle_key = Enum.KeyCode.RightShift, can_resize = true}
do local OldUI = game:GetService("CoreGui"):FindFirstChild("imgui") if OldUI then OldUI:Destroy() end end
local ScreenGui = Instance.new("ScreenGui")
local Prefabs = Instance.new("Frame")
local Label = Instance.new("TextLabel")
local WindowTemplate = Instance.new("ImageLabel")
local Resizer = Instance.new("Frame")
local TitleBar = Instance.new("Frame")
local ToggleButton = Instance.new("ImageButton")
local BarBase = Instance.new("ImageLabel")
local BarTop = Instance.new("ImageLabel")
local TabsContainer = Instance.new("Frame")
local Title = Instance.new("TextLabel")
local TabSelection = Instance.new("ImageLabel")
local TabScrolling = Instance.new("ScrollingFrame")
local TabButtons = Instance.new("Frame")
local TabButtonsLayout = Instance.new("UIListLayout")
local TabDivider = Instance.new("Frame")
local TabTemplate = Instance.new("Frame")
local TabLayout = Instance.new("UIListLayout")
local TextBox = Instance.new("TextBox")
local TextBoxBG = Instance.new("ImageLabel")
local Slider = Instance.new("ImageLabel")
local SliderTitle = Instance.new("TextLabel")
local SliderIndicator = Instance.new("ImageLabel")
local SliderValue = Instance.new("TextLabel")
local SliderBracketR = Instance.new("TextLabel")
local SliderBracketL = Instance.new("TextLabel")
local Circle = Instance.new("ImageLabel")
local HorizontalList = Instance.new("UIListLayout")
local Dropdown = Instance.new("TextButton")
local DropdownArrow = Instance.new("ImageLabel")
local DropdownBox = Instance.new("ImageButton")
local DropdownScroll = Instance.new("ScrollingFrame")
local DropdownLayout = Instance.new("UIListLayout")
local DropdownBG = Instance.new("ImageLabel")
local TabButton = Instance.new("TextButton")
local TabButtonBG = Instance.new("ImageLabel")
local Folder = Instance.new("ImageLabel")
local FolderButton = Instance.new("TextButton")
local FolderButtonBG = Instance.new("ImageLabel")
local FolderToggle = Instance.new("ImageLabel")
local FolderObjects = Instance.new("Frame")
local FolderLayout = Instance.new("UIListLayout")
local HorizontalContainer = Instance.new("Frame")
local HorizontalLayout = Instance.new("UIListLayout")
local Console = Instance.new("ImageLabel")
local ConsoleScroll = Instance.new("ScrollingFrame")
local CodeBox = Instance.new("TextBox")
local SyntaxComments = Instance.new("TextLabel")
local SyntaxGlobals = Instance.new("TextLabel")
local SyntaxKeywords = Instance.new("TextLabel")
local SyntaxRemotes = Instance.new("TextLabel")
local SyntaxStrings = Instance.new("TextLabel")
local SyntaxTokens = Instance.new("TextLabel")
local SyntaxNumbers = Instance.new("TextLabel")
local SyntaxInfo = Instance.new("TextLabel")
local LineNumbers = Instance.new("TextLabel")
local ColorPicker = Instance.new("ImageLabel")
local Palette = Instance.new("ImageLabel")
local PaletteIndicator = Instance.new("ImageLabel")
local ColorSample = Instance.new("ImageLabel")
local Saturation = Instance.new("ImageLabel")
local SaturationIndicator = Instance.new("Frame")
local Switch = Instance.new("TextButton")
local SwitchBG = Instance.new("ImageLabel")
local SwitchTitle = Instance.new("TextLabel")
local Button = Instance.new("TextButton")
local ButtonBG = Instance.new("ImageLabel")
local DropdownBtn = Instance.new("TextButton")
local Keybind = Instance.new("ImageLabel")
local KeybindTitle = Instance.new("TextLabel")
local KeybindInput = Instance.new("TextButton")
local KeybindInputBG = Instance.new("ImageLabel")
local WindowsContainer = Instance.new("Frame")
ScreenGui.Name = "imgui"
ScreenGui.Parent = game:GetService("CoreGui") or gethui()
Prefabs.Name = "Prefabs"
Prefabs.Parent = ScreenGui
Prefabs.BackgroundColor3 = Color3.new(1,1,1)
Prefabs.Size = UDim2.new(0,100,0,100)
Prefabs.Visible = false
Label.Name = "Label"
Label.Parent = Prefabs
Label.BackgroundTransparency = 1
Label.Size = UDim2.new(0,200,0,20)
Label.Font = Enum.Font.FredokaOne
Label.Text = "Hello, world 123"
Label.TextColor3 = Color3.new(1,1,1)
Label.TextSize = 16
Label.TextXAlignment = Enum.TextXAlignment.Left
WindowTemplate.Name = "Window"
WindowTemplate.Parent = Prefabs
WindowTemplate.Active = true
WindowTemplate.BackgroundTransparency = 1
WindowTemplate.ClipsDescendants = true
WindowTemplate.Position = UDim2.new(0,20,0,20)
WindowTemplate.Selectable = true
WindowTemplate.Size = UDim2.new(0,200,0,200)
WindowTemplate.Image = "rbxassetid://2851926732"
WindowTemplate.ImageColor3 = Color3.new(0.082,0.086,0.09)
WindowTemplate.ScaleType = Enum.ScaleType.Slice
WindowTemplate.SliceCenter = Rect.new(12,12,12,12)
Resizer.Name = "Resizer"
Resizer.Parent = WindowTemplate
Resizer.Active = true
Resizer.BackgroundTransparency = 1
Resizer.BorderSizePixel = 0
Resizer.Position = UDim2.new(1,-20,1,-20)
Resizer.Size = UDim2.new(0,20,0,20)
TitleBar.Name = "Bar"
TitleBar.Parent = WindowTemplate
TitleBar.BackgroundColor3 = Color3.new(0.161,0.29,0.478)
TitleBar.BorderSizePixel = 0
TitleBar.Position = UDim2.new(0,0,0,5)
TitleBar.Size = UDim2.new(1,0,0,15)
ToggleButton.Name = "Toggle"
ToggleButton.Parent = TitleBar
ToggleButton.BackgroundTransparency = 1
ToggleButton.Position = UDim2.new(0,5,0,-2)
ToggleButton.Size = UDim2.new(0,20,0,20)
ToggleButton.ZIndex = 2
ToggleButton.Image = "https://www.roblox.com/Thumbs/Asset.ashx?width=420&height=420&assetId=87010024089623"
BarBase.Name = "Base"
BarBase.Parent = TitleBar
BarBase.BackgroundColor3 = Color3.new(0.161,0.29,0.478)
BarBase.BorderSizePixel = 0
BarBase.Position = UDim2.new(0,0,0.8,0)
BarBase.Size = UDim2.new(1,0,0,10)
BarBase.Image = "rbxassetid://2851926732"
BarBase.ImageColor3 = Color3.new(0.161,0.29,0.478)
BarBase.ScaleType = Enum.ScaleType.Slice
BarBase.SliceCenter = Rect.new(12,12,12,12)
BarTop.Name = "Top"
BarTop.Parent = TitleBar
BarTop.BackgroundTransparency = 1
BarTop.Position = UDim2.new(0,0,0,-5)
BarTop.Size = UDim2.new(1,0,0,10)
BarTop.Image = "rbxassetid://2851926732"
BarTop.ImageColor3 = Color3.new(0.161,0.29,0.478)
BarTop.ScaleType = Enum.ScaleType.Slice
BarTop.SliceCenter = Rect.new(12,12,12,12)
TabsContainer.Name = "Tabs"
TabsContainer.Parent = WindowTemplate
TabsContainer.BackgroundTransparency = 1
TabsContainer.Position = UDim2.new(0,15,0,60)
TabsContainer.Size = UDim2.new(1,-30,1,-60)
TabsContainer.ClipsDescendants = true
Title.Name = "Title"
Title.Parent = WindowTemplate
Title.BackgroundTransparency = 1
Title.Position = UDim2.new(0,30,0,3)
Title.Size = UDim2.new(0,200,0,20)
Title.Font = Enum.Font.FredokaOne
Title.Text = "Gamer Time"
Title.TextColor3 = Color3.new(1,1,1)
Title.TextSize = 16
Title.TextXAlignment = Enum.TextXAlignment.Left
TabSelection.Name = "TabSelection"
TabSelection.Parent = WindowTemplate
TabSelection.BackgroundTransparency = 1
TabSelection.Position = UDim2.new(0,15,0,30)
TabSelection.Size = UDim2.new(1,-30,0,25)
TabSelection.Visible = false
TabSelection.Image = "rbxassetid://2851929490"
TabSelection.ImageColor3 = Color3.new(0.145,0.149,0.157)
TabSelection.ScaleType = Enum.ScaleType.Slice
TabSelection.SliceCenter = Rect.new(4,4,4,4)
TabScrolling.Name = "TabScrolling"
TabScrolling.Parent = TabSelection
TabScrolling.BackgroundTransparency = 1
TabScrolling.BorderSizePixel = 0
TabScrolling.Size = UDim2.new(1,0,1,0)
TabScrolling.CanvasSize = UDim2.new(0,0,1,0)
TabScrolling.ScrollBarThickness = 0
TabScrolling.ScrollingDirection = Enum.ScrollingDirection.X
TabButtons.Name = "TabButtons"
TabButtons.Parent = TabScrolling
TabButtons.BackgroundTransparency = 1
TabButtons.Size = UDim2.new(0,0,1,0)
TabButtons.ClipsDescendants = true
TabButtonsLayout.Parent = TabButtons
TabButtonsLayout.FillDirection = Enum.FillDirection.Horizontal
TabButtonsLayout.SortOrder = Enum.SortOrder.LayoutOrder
TabButtonsLayout.Padding = UDim.new(0,2)
TabDivider.Parent = TabSelection
TabDivider.BackgroundColor3 = Color3.new(0.125,0.227,0.373)
TabDivider.BorderColor3 = Color3.new(0.106,0.165,0.208)
TabDivider.BorderSizePixel = 0
TabDivider.Position = UDim2.new(0,0,1,0)
TabDivider.Size = UDim2.new(1,0,0,2)
TabTemplate.Name = "Tab"
TabTemplate.Parent = Prefabs
TabTemplate.BackgroundTransparency = 1
TabTemplate.Size = UDim2.new(1,0,1,0)
TabTemplate.Visible = false
TabLayout.Parent = TabTemplate
TabLayout.SortOrder = Enum.SortOrder.LayoutOrder
TabLayout.Padding = UDim.new(0,5)
TextBox.Parent = Prefabs
TextBox.BackgroundTransparency = 1
TextBox.BorderSizePixel = 0
TextBox.Size = UDim2.new(1,0,0,20)
TextBox.ZIndex = 2
TextBox.Font = Enum.Font.FredokaOne
TextBox.PlaceholderColor3 = Color3.new(0.698,0.698)
TextBox.PlaceholderText = "Input Text"
TextBox.Text = ""
TextBox.TextColor3 = Color3.new(0.784,0.784)
TextBox.TextSize = 14
TextBoxBG.Name = "TextBox_Roundify_4px"
TextBoxBG.Parent = TextBox
TextBoxBG.BackgroundTransparency = 1
TextBoxBG.Size = UDim2.new(1,0,1,0)
TextBoxBG.Image = "rbxassetid://2851929490"
TextBoxBG.ImageColor3 = Color3.new(0.204,0.208,0.22)
TextBoxBG.ScaleType = Enum.ScaleType.Slice
TextBoxBG.SliceCenter = Rect.new(4,4,4)
Slider.Name = "Slider"
Slider.Parent = Prefabs
Slider.BackgroundTransparency = 1
Slider.Position = UDim2.new(0,0,0.179,0)
Slider.Size = UDim2.new(1,0,0,20)
Slider.Image = "rbxassetid://2851929490"
Slider.ImageColor3 = Color3.new(0.145,0.149,0.157)
Slider.ScaleType = Enum.ScaleType.Slice
Slider.SliceCenter = Rect.new(4,4,4,4)
SliderTitle.Name = "Title"
SliderTitle.Parent = Slider
SliderTitle.BackgroundTransparency = 1
SliderTitle.Position = UDim2.new(0.5,0,0.5,-10)
SliderTitle.Size = UDim2.new(0,0,0,20)
SliderTitle.ZIndex = 2
SliderTitle.Font = Enum.Font.FredokaOne
SliderTitle.Text = "Slider"
SliderTitle.TextColor3 = Color3.new(0.784,0.784)
SliderTitle.TextSize = 14
SliderIndicator.Name = "Indicator"
SliderIndicator.Parent = Slider
SliderIndicator.BackgroundTransparency = 1
SliderIndicator.Size = UDim2.new(0,0,0,20)
SliderIndicator.Image = "rbxassetid://2851929490"
SliderIndicator.ImageColor3 = Color3.new(0.255,0.263,0.278)
SliderIndicator.ScaleType = Enum.ScaleType.Slice
SliderIndicator.SliceCenter = Rect.new(4,4,4,4)
SliderValue.Name = "Value"
SliderValue.Parent = Slider
SliderValue.BackgroundTransparency = 1
SliderValue.Position = UDim2.new(1,-55,0.5,-10)
SliderValue.Size = UDim2.new(0,50,0,20)
SliderValue.Font = Enum.Font.FredokaOne
SliderValue.Text = "0%"
SliderValue.TextColor3 = Color3.new(0.784,0.784)
SliderValue.TextSize = 14
SliderBracketR.Parent = Slider
SliderBracketR.BackgroundTransparency = 1
SliderBracketR.Position = UDim2.new(1,-20,-0.75,0)
SliderBracketR.Size = UDim2.new(0,26,0,50)
SliderBracketR.Font = Enum.Font.FredokaOne
SliderBracketR.Text = "]"
SliderBracketR.TextColor3 = Color3.new(0.627,0.627)
SliderBracketR.TextSize = 14
SliderBracketL.Parent = Slider
SliderBracketL.BackgroundTransparency = 1
SliderBracketL.Position = UDim2.new(1,-65,-0.75,0)
SliderBracketL.Size = UDim2.new(0,26,0,50)
SliderBracketL.Font = Enum.Font.FredokaOne
SliderBracketL.Text = "["
SliderBracketL.TextColor3 = Color3.new(0.627,0.627)
SliderBracketL.TextSize = 14
Circle.Name = "Circle"
Circle.Parent = Prefabs
Circle.BackgroundTransparency = 1
Circle.Image = "rbxassetid://266543268"
Circle.ImageTransparency = 0.5
HorizontalList.Parent = Prefabs
HorizontalList.FillDirection = Enum.FillDirection.Horizontal
HorizontalList.SortOrder = Enum.SortOrder.LayoutOrder
HorizontalList.Padding = UDim.new(0,20)
Dropdown.Name = "Dropdown"
Dropdown.Parent = Prefabs
Dropdown.BackgroundTransparency = 1
Dropdown.BorderSizePixel = 0
Dropdown.Position = UDim2.new(-0.056,0,0.083,0)
Dropdown.Size = UDim2.new(0,200,0,20)
Dropdown.ZIndex = 2
Dropdown.Font = Enum.Font.FredokaOne
Dropdown.Text = "      Dropdown"
Dropdown.TextColor3 = Color3.new(0.784,0.784)
Dropdown.TextSize = 14
Dropdown.TextXAlignment = Enum.TextXAlignment.Left
DropdownArrow.Name = "Indicator"
DropdownArrow.Parent = Dropdown
DropdownArrow.BackgroundTransparency = 1
DropdownArrow.Position = UDim2.new(0.9,-10,0.1,0)
DropdownArrow.Rotation = -90
DropdownArrow.Size = UDim2.new(0,15,0,15)
DropdownArrow.ZIndex = 2
DropdownArrow.Image = "https://www.roblox.com/Thumbs/Asset.ashx?width=420&height=420&assetId=4744658743"
DropdownBox.Name = "Box"
DropdownBox.Parent = Dropdown
DropdownBox.BackgroundTransparency = 1
DropdownBox.Position = UDim2.new(0,0,0,25)
DropdownBox.Size = UDim2.new(1,0,0,150)
DropdownBox.ZIndex = 3
DropdownBox.Image = "rbxassetid://2851929490"
DropdownBox.ImageColor3 = Color3.new(0.129,0.133,0.141)
DropdownBox.ScaleType = Enum.ScaleType.Slice
DropdownBox.SliceCenter = Rect.new(4,4,4,4)
DropdownScroll.Name = "Objects"
DropdownScroll.Parent = DropdownBox
DropdownScroll.BackgroundTransparency = 1
DropdownScroll.BorderSizePixel = 0
DropdownScroll.Size = UDim2.new(1,0,1,0)
DropdownScroll.ZIndex = 3
DropdownScroll.CanvasSize = UDim2.new(0,0,0,0)
DropdownScroll.ScrollBarThickness = 4
DropdownScroll.ScrollBarImageColor3 = Color3.fromRGB(255,0,0)
DropdownLayout.Parent = DropdownScroll
DropdownLayout.SortOrder = Enum.SortOrder.LayoutOrder
DropdownBG.Name = "TextButton_Roundify_4px"
DropdownBG.Parent = Dropdown
DropdownBG.BackgroundTransparency = 1
DropdownBG.Size = UDim2.new(1,0,1,0)
DropdownBG.Image = "rbxassetid://2851929490"
DropdownBG.ImageColor3 = Color3.new(0.204,0.208,0.22)
DropdownBG.ScaleType = Enum.ScaleType.Slice
DropdownBG.SliceCenter = Rect.new(4,4,4,4)
TabButton.Name = "TabButton"
TabButton.Parent = Prefabs
TabButton.BackgroundColor3 = Color3.new(0.161,0.29,0.478)
TabButton.BackgroundTransparency = 1
TabButton.BorderSizePixel = 0
TabButton.Position = UDim2.new(0.185,0,0,0)
TabButton.Size = UDim2.new(0,71,0,20)
TabButton.ZIndex = 2
TabButton.Font = Enum.Font.FredokaOne
TabButton.Text = "Test tab"
TabButton.TextColor3 = Color3.new(0.784,0.784)
TabButton.TextSize = 14
TabButtonBG.Name = "TextButton_Roundify_4px"
TabButtonBG.Parent = TabButton
TabButtonBG.BackgroundTransparency = 1
TabButtonBG.Size = UDim2.new(1,0,1,0)
TabButtonBG.Image = "rbxassetid://2851929490"
TabButtonBG.ImageColor3 = Color3.new(0.204,0.208,0.22)
TabButtonBG.ScaleType = Enum.ScaleType.Slice
TabButtonBG.SliceCenter = Rect.new(4,4,4,4)
Folder.Name = "Folder"
Folder.Parent = Prefabs
Folder.BackgroundTransparency = 1
Folder.Position = UDim2.new(0,0,0,50)
Folder.Size = UDim2.new(1,0,0,20)
Folder.Image = "rbxassetid://2851929490"
Folder.ImageColor3 = Color3.new(0.082,0.086,0.09)
Folder.ScaleType = Enum.ScaleType.Slice
Folder.SliceCenter = Rect.new(4,4,4,4)
FolderButton.Name = "Button"
FolderButton.Parent = Folder
FolderButton.BackgroundColor3 = Color3.new(0.161,0.29,0.478)
FolderButton.BackgroundTransparency = 1
FolderButton.BorderSizePixel = 0
FolderButton.Size = UDim2.new(1,0,0,20)
FolderButton.ZIndex = 2
FolderButton.Font = Enum.Font.FredokaOne
FolderButton.Text = "      Folder"
FolderButton.TextColor3 = Color3.new(1,1,1)
FolderButton.TextSize = 14
FolderButton.TextXAlignment = Enum.TextXAlignment.Left
FolderButtonBG.Name = "TextButton_Roundify_4px"
FolderButtonBG.Parent = FolderButton
FolderButtonBG.BackgroundTransparency = 1
FolderButtonBG.Size = UDim2.new(1,0,1,0)
FolderButtonBG.Image = "rbxassetid://2851929490"
FolderButtonBG.ImageColor3 = Color3.new(0.161,0.29,0.478)
FolderButtonBG.ScaleType = Enum.ScaleType.Slice
FolderButtonBG.SliceCenter = Rect.new(4,4)
FolderToggle.Name = "Toggle"
FolderToggle.Parent = FolderButton
FolderToggle.BackgroundTransparency = 1
FolderToggle.Position = UDim2.new(0,5,0,0)
FolderToggle.Size = UDim2.new(0,20,0,20)
FolderToggle.Image = "https://www.roblox.com/Thumbs/Asset.ashx?width=420&height=420&assetId=4731371541"
FolderObjects.Name = "Objects"
FolderObjects.Parent = Folder
FolderObjects.BackgroundTransparency = 1
FolderObjects.Position = UDim2.new(0,10,0,25)
FolderObjects.Size = UDim2.new(1,-10,1,-25)
FolderObjects.Visible = false
FolderLayout.Parent = FolderObjects
FolderLayout.SortOrder = Enum.SortOrder.LayoutOrder
FolderLayout.Padding = UDim.new(0,5)
HorizontalContainer.Name = "HorizontalAlignment"
HorizontalContainer.Parent = Prefabs
HorizontalContainer.BackgroundTransparency = 1
HorizontalContainer.Size = UDim2.new(1,0,0,20)
HorizontalLayout.Parent = HorizontalContainer
HorizontalLayout.FillDirection = Enum.FillDirection.Horizontal
HorizontalLayout.SortOrder = Enum.SortOrder.LayoutOrder
HorizontalLayout.Padding = UDim.new(0,5)
Console.Name = "Console"
Console.Parent = Prefabs
Console.BackgroundTransparency = 1
Console.Size = UDim2.new(1,0,0,200)
Console.Image = "rbxassetid://2851928141"
Console.ImageColor3 = Color3.new(0.129,0.133,0.141)
Console.ScaleType = Enum.ScaleType.Slice
Console.SliceCenter = Rect.new(8,8,8,8)
ConsoleScroll.Parent = Console
ConsoleScroll.BackgroundTransparency = 1
ConsoleScroll.BorderSizePixel = 0
ConsoleScroll.Size = UDim2.new(1,0,1)
ConsoleScroll.CanvasSize = UDim2.new(0,0,0,0)
ConsoleScroll.ScrollBarThickness = 4
CodeBox.Name = "Source"
CodeBox.Parent = ConsoleScroll
CodeBox.BackgroundTransparency = 1
CodeBox.Position = UDim2.new(0,40,0,0)
CodeBox.Size = UDim2.new(1,-40,0,10000)
CodeBox.ZIndex = 3
CodeBox.ClearTextOnFocus = false
CodeBox.Font = Enum.Font.Code
CodeBox.MultiLine = true
CodeBox.PlaceholderColor3 = Color3.new(0.8,0.8,0.8)
CodeBox.Text = ""
CodeBox.TextColor3 = Color3.new(1,1,1)
CodeBox.TextSize = 15
CodeBox.TextStrokeColor3 = Color3.new(1,1,1)
CodeBox.TextWrapped = true
CodeBox.TextXAlignment = Enum.TextXAlignment.Left
CodeBox.TextYAlignment = Enum.TextYAlignment.Top
SyntaxComments.Name = "Comments"
SyntaxComments.Parent = CodeBox
SyntaxComments.BackgroundTransparency = 1
SyntaxComments.Size = UDim2.new(1,0,1,0)
SyntaxComments.ZIndex = 5
SyntaxComments.Font = Enum.Font.Code
SyntaxComments.Text = ""
SyntaxComments.TextColor3 = Color3.new(0.231,0.784,0.231)
SyntaxComments.TextSize = 15
SyntaxComments.TextXAlignment = Enum.TextXAlignment.Left
SyntaxComments.TextYAlignment = Enum.TextYAlignment.Top
SyntaxGlobals.Name = "Globals"
SyntaxGlobals.Parent = CodeBox
SyntaxGlobals.BackgroundTransparency = 1
SyntaxGlobals.Size = UDim2.new(1,0,1,0)
SyntaxGlobals.ZIndex = 5
SyntaxGlobals.Font = Enum.Font.Code
SyntaxGlobals.Text = ""
SyntaxGlobals.TextColor3 = Color3.new(0.518,0.839,0.969)
SyntaxGlobals.TextSize = 15
SyntaxGlobals.TextXAlignment = Enum.TextXAlignment.Left
SyntaxGlobals.TextYAlignment = Enum.TextYAlignment.Top
SyntaxKeywords.Name = "Keywords"
SyntaxKeywords.Parent = CodeBox
SyntaxKeywords.BackgroundTransparency = 1
SyntaxKeywords.Size = UDim2.new(1,0,1,0)
SyntaxKeywords.ZIndex = 5
SyntaxKeywords.Font = Enum.Font.Code
SyntaxKeywords.Text = ""
SyntaxKeywords.TextColor3 = Color3.new(0.973,0.427,0.486)
SyntaxKeywords.TextSize = 15
SyntaxKeywords.TextXAlignment = Enum.TextXAlignment.Left
SyntaxKeywords.TextYAlignment = Enum.TextYAlignment.Top
SyntaxRemotes.Name = "RemoteHighlight"
SyntaxRemotes.Parent = CodeBox
SyntaxRemotes.BackgroundTransparency = 1
SyntaxRemotes.Size = UDim2.new(1,0,1,0)
SyntaxRemotes.ZIndex = 5
SyntaxRemotes.Font = Enum.Font.Code
SyntaxRemotes.Text = ""
SyntaxRemotes.TextColor3 = Color3.new(0,0.569,1)
SyntaxRemotes.TextSize = 15
SyntaxRemotes.TextXAlignment = Enum.TextXAlignment.Left
SyntaxRemotes.TextYAlignment = Enum.TextYAlignment.Top
SyntaxStrings.Name = "Strings"
SyntaxStrings.Parent = CodeBox
SyntaxStrings.BackgroundTransparency = 1
SyntaxStrings.Size = UDim2.new(1,0,1,0)
SyntaxStrings.ZIndex = 5
SyntaxStrings.Font = Enum.Font.Code
SyntaxStrings.Text = ""
SyntaxStrings.TextColor3 = Color3.new(0.678,0.945,0.584)
SyntaxStrings.TextSize = 15
SyntaxStrings.TextXAlignment = Enum.TextXAlignment.Left
SyntaxStrings.TextYAlignment = Enum.TextYAlignment.Top
SyntaxTokens.Name = "Tokens"
SyntaxTokens.Parent = CodeBox
SyntaxTokens.BackgroundTransparency = 1
SyntaxTokens.Size = UDim2.new(1,0,1,0)
SyntaxTokens.ZIndex = 5
SyntaxTokens.Font = Enum.Font.Code
SyntaxTokens.Text = ""
SyntaxTokens.TextColor3 = Color3.new(1,1,1)
SyntaxTokens.TextSize = 15
SyntaxTokens.TextXAlignment = Enum.TextXAlignment.Left
SyntaxTokens.TextYAlignment = Enum.TextYAlignment.Top
SyntaxNumbers.Name = "Numbers"
SyntaxNumbers.Parent = CodeBox
SyntaxNumbers.BackgroundTransparency = 1
SyntaxNumbers.Size = UDim2.new(1,0,1,0)
SyntaxNumbers.ZIndex = 4
SyntaxNumbers.Font = Enum.Font.Code
SyntaxNumbers.Text = ""
SyntaxNumbers.TextColor3 = Color3.new(1,0.776,0)
SyntaxNumbers.TextSize = 15
SyntaxNumbers.TextXAlignment = Enum.TextXAlignment.Left
SyntaxNumbers.TextYAlignment = Enum.TextYAlignment.Top
SyntaxInfo.Name = "Info"
SyntaxInfo.Parent = CodeBox
SyntaxInfo.BackgroundTransparency = 1
SyntaxInfo.Size = UDim2.new(1,0,1,0)
SyntaxInfo.ZIndex = 5
SyntaxInfo.Font = Enum.Font.Code
SyntaxInfo.Text = ""
SyntaxInfo.TextColor3 = Color3.new(0,0.635,1)
SyntaxInfo.TextSize = 15
SyntaxInfo.TextXAlignment = Enum.TextXAlignment.Left
SyntaxInfo.TextYAlignment = Enum.TextYAlignment.Top
LineNumbers.Name = "Lines"
LineNumbers.Parent = ConsoleScroll
LineNumbers.BackgroundTransparency = 1
LineNumbers.BorderSizePixel = 0
LineNumbers.Size = UDim2.new(0,40,0,10000)
LineNumbers.ZIndex = 4
LineNumbers.Font = Enum.Font.Code
LineNumbers.Text = "1\n"
LineNumbers.TextColor3 = Color3.new(1,1,1)
LineNumbers.TextSize = 15
LineNumbers.TextWrapped = true
LineNumbers.TextYAlignment = Enum.TextYAlignment.Top
ColorPicker.Name = "ColorPicker"
ColorPicker.Parent = Prefabs
ColorPicker.BackgroundTransparency = 1
ColorPicker.Size = UDim2.new(0,180,0,110)
ColorPicker.Image = "rbxassetid://2851929490"
ColorPicker.ImageColor3 = Color3.new(0.204,0.208,0.22)
ColorPicker.ScaleType = Enum.ScaleType.Slice
ColorPicker.SliceCenter = Rect.new(4,4,4,4)
Palette.Name = "Palette"
Palette.Parent = ColorPicker
Palette.BackgroundTransparency = 1
Palette.Position = UDim2.new(0.05,0,0.05,0)
Palette.Size = UDim2.new(0,100,0,100)
Palette.Image = "rbxassetid://698052001"
Palette.ScaleType = Enum.ScaleType.Slice
Palette.SliceCenter = Rect.new(4,4,4,4)
PaletteIndicator.Name = "Indicator"
PaletteIndicator.Parent = Palette
PaletteIndicator.BackgroundTransparency = 1
PaletteIndicator.Size = UDim2.new(0,5,0,5)
PaletteIndicator.ZIndex = 2
PaletteIndicator.Image = "rbxassetid://2851926732"
PaletteIndicator.ImageColor3 = Color3.new(0,0,0)
PaletteIndicator.ScaleType = Enum.ScaleType.Slice
PaletteIndicator.SliceCenter = Rect.new(12,12,12,12)
ColorSample.Name = "Sample"
ColorSample.Parent = ColorPicker
ColorSample.BackgroundTransparency = 1
ColorSample.Position = UDim2.new(0.8,0,0.05,0)
ColorSample.Size = UDim2.new(0,25,0,25)
ColorSample.Image = "rbxassetid://2851929490"
ColorSample.ScaleType = Enum.ScaleType.Slice
ColorSample.SliceCenter = Rect.new(4,4,4,4)
Saturation.Name = "Saturation"
Saturation.Parent = ColorPicker
Saturation.BackgroundColor3 = Color3.new(1,1,1)
Saturation.Position = UDim2.new(0.65,0,0.05,0)
Saturation.Size = UDim2.new(0,15,0,100)
Saturation.Image = "rbxassetid://3641079629"
SaturationIndicator.Name = "Indicator"
SaturationIndicator.Parent = Saturation
SaturationIndicator.BackgroundColor3 = Color3.new(1,1,1)
SaturationIndicator.BorderSizePixel = 0
SaturationIndicator.Size = UDim2.new(0,20,0,2)
SaturationIndicator.ZIndex = 2
Switch.Name = "Switch"
Switch.Parent = Prefabs
Switch.BackgroundTransparency = 1
Switch.BorderSizePixel = 0
Switch.Position = UDim2.new(0.229,0,0.207,0)
Switch.Size = UDim2.new(0,20,0,20)
Switch.ZIndex = 2
Switch.Font = Enum.Font.SourceSans
Switch.Text = ""
Switch.TextColor3 = Color3.new(1,1,1)
Switch.TextSize = 14
SwitchBG.Name = "TextButton_Roundify_4px"
SwitchBG.Parent = Switch
SwitchBG.BackgroundTransparency = 1
SwitchBG.Size = UDim2.new(1,0,1,0)
SwitchBG.Image = "rbxassetid://2851929490"
SwitchBG.ImageColor3 = Color3.new(0.161,0.29,0.478)
SwitchBG.ImageTransparency = 0.5
SwitchBG.ScaleType = Enum.ScaleType.Slice
SwitchBG.SliceCenter = Rect.new(4,4,4,4)
SwitchTitle.Name = "Title"
SwitchTitle.Parent = Switch
SwitchTitle.BackgroundTransparency = 1
SwitchTitle.Position = UDim2.new(1.2,0,0,0)
SwitchTitle.Size = UDim2.new(0,20,0,20)
SwitchTitle.Font = Enum.Font.FredokaOne
SwitchTitle.Text = "Switch"
SwitchTitle.TextColor3 = Color3.new(0.784,0.784)
SwitchTitle.TextSize = 14
SwitchTitle.TextXAlignment = Enum.TextXAlignment.Left
Button.Name = "Button"
Button.Parent = Prefabs
Button.BackgroundColor3 = Color3.new(0.161,0.29,0.478)
Button.BackgroundTransparency = 1
Button.BorderSizePixel = 0
Button.Size = UDim2.new(0,91,0,20)
Button.ZIndex = 2
Button.Font = Enum.Font.FredokaOne
Button.TextColor3 = Color3.new(1,1,1)
Button.TextSize = 14
ButtonBG.Name = "TextButton_Roundify_4px"
ButtonBG.Parent = Button
ButtonBG.BackgroundTransparency = 1
ButtonBG.Size = UDim2.new(1,0,1,0)
ButtonBG.Image = "rbxassetid://2851929490"
ButtonBG.ImageColor3 = Color3.new(0.161,0.29,0.478)
ButtonBG.ScaleType = Enum.ScaleType.Slice
ButtonBG.SliceCenter = Rect.new(4,4,4,4)
DropdownBtn.Name = "DropdownButton"
DropdownBtn.Parent = Prefabs
DropdownBtn.BackgroundColor3 = Color3.new(0.129,0.133,0.141)
DropdownBtn.BorderSizePixel = 0
DropdownBtn.Size = UDim2.new(1,0,0,20)
DropdownBtn.ZIndex = 3
DropdownBtn.Font = Enum.Font.FredokaOne
DropdownBtn.Text = "      Button"
DropdownBtn.TextColor3 = Color3.new(0.784,0.784)
DropdownBtn.TextSize = 14
DropdownBtn.TextXAlignment = Enum.TextXAlignment.Left
Keybind.Name = "Keybind"
Keybind.Parent = Prefabs
Keybind.BackgroundTransparency = 1
Keybind.Size = UDim2.new(0,200,0,20)
Keybind.Image = "rbxassetid://2851929490"
Keybind.ImageColor3 = Color3.new(0.204,0.208,0.22)
Keybind.ScaleType = Enum.ScaleType.Slice
Keybind.SliceCenter = Rect.new(4,4)
KeybindTitle.Name = "Title"
KeybindTitle.Parent = Keybind
KeybindTitle.BackgroundTransparency = 1
KeybindTitle.Size = UDim2.new(0,0,1,0)
KeybindTitle.Font = Enum.Font.FredokaOne
KeybindTitle.Text = "Keybind"
KeybindTitle.TextColor3 = Color3.new(0.784,0.784)
KeybindTitle.TextSize = 14
KeybindTitle.TextXAlignment = Enum.TextXAlignment.Left
KeybindInput.Name = "Input"
KeybindInput.Parent = Keybind
KeybindInput.BackgroundTransparency = 1
KeybindInput.BorderSizePixel = 0
KeybindInput.Position = UDim2.new(1,-85,0,2)
KeybindInput.Size = UDim2.new(0,80,1,-4)
KeybindInput.ZIndex = 2
KeybindInput.Font = Enum.Font.FredokaOne
KeybindInput.Text = "RShift"
KeybindInput.TextColor3 = Color3.new(0.784,0.784)
KeybindInput.TextSize = 12
KeybindInput.TextWrapped = true
KeybindInputBG.Name = "Input_Roundify_4px"
KeybindInputBG.Parent = KeybindInput
KeybindInputBG.BackgroundTransparency = 1
KeybindInputBG.Size = UDim2.new(1,0,1,0)
KeybindInputBG.Image = "rbxassetid://2851929490"
KeybindInputBG.ImageColor3 = Color3.new(0.29,0.294,0.314)
KeybindInputBG.ScaleType = Enum.ScaleType.Slice
KeybindInputBG.SliceCenter = Rect.new(4,4)
WindowsContainer.Name = "Windows"
WindowsContainer.Parent = ScreenGui
WindowsContainer.BackgroundTransparency = 1
WindowsContainer.Position = UDim2.new(0,20,0,20)
WindowsContainer.Size = UDim2.new(1,20,1,-20)
script.Parent = ScreenGui
local UserInputService = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")
local RunService = game:GetService("RunService")
local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer
local Mouse = LocalPlayer:GetMouse()
local Prefabs = script.Parent:WaitForChild("Prefabs")
local WindowsContainer = script.Parent:FindFirstChild("Windows")
local BindingState = {binding = false}
local Connections = {}
local function Connect(connection) table.insert(Connections, connection) return connection end
local function DisconnectAll() for _,connection in ipairs(Connections) do if connection.Connected then connection:Disconnect() end end Connections = {} end
Connect(UserInputService.InputBegan:Connect(function(input, gameProcessed) if input.KeyCode == (typeof(Library.toggle_key) == "EnumItem" and Library.toggle_key or Enum.KeyCode.RightShift) then if script.Parent and not BindingState.binding then script.Parent.Enabled = not script.Parent.Enabled end))
local function TweenObject(object, properties, time) time = time or 0.1 if time == 0 then for prop, val in pairs(properties) do object[prop
